### ISSUE TITLE
Please advise on the derivation process of York's confidence interval

### ISSUE THREAD

**Issue by flypigeon** [davidbajnai/isogeochem#3]
Hello,

I've recently been working on the problem of least squares fitting in isotopic age calculations, which involves the calculation of confidence intervals.

When I calculate the confidence interval with the ordinary least squares method, this method does not satisfy the data with errors and correlation coefficients.

Then I came across your paper "Empirical calibration of the clumped isotope paleothermometer using calcites of various origins" in the process of searching.

it mentions how the confidence interval is determined during least squares fitting for data with errors and correlation coefficients, but there is no calculation step in the article, which you mentioned in appendix a., but it's just a link, and you don't see the derivation step.

Because I hope to learn this derivation step by myself, I hope you can provide the derivation step of the confidence interval.

ths!

**Comment by davidbajnai** [comment]
Hi @flypigeon,
If you are interested in the code used for the Wacker et al. (2014) paper, have a look at the  [R/york.R](york.R) code in this repo. It is based on what is outlined in York et al. (2004) Unified equations for the slope, intercept, and standard errors of the best straight line.
D
